home:
  path: /
  controller: App\Controller\WebsiteController::home

shop:
  path: /shop
  controller: App\Controller\WebsiteController::shop

about:
  path: /about
  controller: App\Controller\WebsiteController::about
